# Generated by Django 5.2.17 on 2026-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
