# Generated by Django 5.2.17 on 2026-09-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_failedloginattempt_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='expected_completion',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ministry',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['state', 'district'], name='monitoring__state_ee16a4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'risk_level'], name='monitoring__status_24c45b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['ministry', 'status'], name='monitoring__ministr_e896e0_idx'),
        ),
    ]
