# Generated by Django 5.2.17 on 2026-09-19 08:03

from django.db import migrations, models


def set_must_reset_for_existing(apps, schema_editor):
    UserProfile = apps.get_model('monitoring', 'UserProfile')
    UserProfile.objects.all().update(must_reset_password=True)

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_project_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_must_reset_for_existing, reverse_code=migrations.RunPython.noop),
    ]
